language: node_js
node_js:
  - "6"
addons:
  sonarqube: true
env:
  global:
    - secure: "PwyJ78Z5B0hEXWD6HtnKqhFLjmz/qL2fShKfSUHpRLqOvPoxtaVOa97Efroz2B3aNRzr6aBU48lNyQtY5yut7aw1fL8IiCsPbR2wzgwI8nnvzVdUQP/HNA5VFb5LNipT7+G6bNJumwXbQXqKtysjqm9DBqGCi9uLf1/k3oHF/PX2qON8LtVGgf1D90S28VcYZOl6zbWcaxzjjnz6fqv4OVXHnZ1AiwKiQA+lsADVYI847qfNoCIBkPxbUfpShskd7NdK6OIqayOXetkwjvSp+nPEcjlHWseyzS6bIoGAlAr3sx7fPZad9unLUwLlWRGr2IdG7/K9l8O/eGuZd+6vP5cMY0DCbi8Rz/Y6GjwH/oKS3lIMCTuixi6icXxBjCVE8tu0s+HT4MfLzohSVm0R3bWoZquiXsNYx4OVPNY9eFoIWd04nUgzkKUU9O3YCMSlX0ETh3niWfQm0ERryU/m7GMaRAgCMiH4ANXJhbTUuCMvNIRlHGu/m2tPcJ1RAXDuRIQJVfRJFOS7Ec0hTpk5s7r8yPfqTbgIDtzAmJUYZAx7ZivWGnXGA8xxBHSekylZB/vqCUMyyD4ezU0lpGkbQ3AJHaBmsZ32NDBk50GXZE2TC37QuJ4mv9i2iVCALRjksvT+PKyGKJdZK9O4vrE1uvW1ny6kNYN2Apf2lYEkfAc="
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN